### ISSUE TITLE
I have a doubt

### ISSUE THREAD

**Issue by zhentaozhang** [XYH0118/EEGDfus#1]

**Comment by XYH0118** [comment]
Dear Prof. Dr. Znang,




Thank you for your message. I apologize for the confusion regarding the "ssed" dataset. To clarify, I have attached the relevant article that contains the dataset for your reference.




Please feel free to reach out if you have any further questions or need additional information.




Best regards,
Xiaoyang Huang










-----原始邮件-----
发件人:zhentaozhang ***@***.***>
发送时间:2024-12-15 17:37:30 (星期日)
收件人: XYH0118/EEGDfus ***@***.***>
抄送: Subscribed ***@***.***>
主题: [XYH0118/EEGDfus] I have a doubt (Issue #1)






Dear Author,

I hope this message finds you well. I have noticed a potential issue with the "ssed" dataset mentioned in your paper and code. I am unable to locate the contents of this dataset, although I did find a file named "denoising_model_see.py" in your code repository. Could you please clarify whether there might be a typographical error or provide more information about the dataset?

Thank you for your attention to this matter.
